### ISSUE TITLE
Chat Delay takes 15-30 seconds to show on stream is it possible to lower it?

### ISSUE THREAD

**Issue by Krushchevawn** [sunshinekitty/TwitchPlaysPokemon#3]
I have the ircbot.py and controller.py running. It opens the VBA Emulator, and everything is working it connects to my chat. I type in like start and it instantly does it on the Emulator. But thats when im not streaming. Im using a program called XSplit Broadcaster. Which is what im using to stream the audio and video and also show recent commands inputed. When i start streaming. I see the game and hear the game sounds i type in the chat start and on controller.py and ircbot.py it shows ive inputed the start button and the emulator goes to the main menu. But on stream. I have to wait 15-30 seconds before it shows what command was inputed and before it shows it on the video. Is there any possible way. I can make this shorter?? I dont like waiting 15-30 seconds before i see what my command did. So is there any way to lower the chat delay?

**Comment by sunshinekitty** [comment]
Thanks for your question!

You'll see a lot of streamers out there running this saying it's an issue with Twitch's chat servers and that Twitch has been slow.  Unfortunately this isn't the case and it's more of an un-fixable issue, as you have seen things are instant on this side of things.

Where you run into issues is that the broadcasting program has to encode the video, upload it and in a few cases Twitch re-encodes that video, then broadcasts it.  The only way to resolve this issue would be to get very quick internet, but to a point it becomes impossible to have immediate results because of the delay in place made by Twitch.

If you are serious about this and a developer as well look into setting up a RMTP server, this would take away the need for Twitch and you could host from your own site where you can control the amount of bandwidth and get better results from Twitch based on how much you put into it.

**Comment by Krushchevawn** [comment]
Well. Im doing this for my own fun. I am a developer and you did say there was some type of chat delay.. is there a way to lower this? Im not looking to get rid of the delay. Just make it not s long? im not looking to make it completely live or anything. I just want a better reault for a delay like 5-10 seconds or 10-15 seconds instead of 15-30. Is there any possible solution to this?

**Comment by sunshinekitty** [comment]
As I said this isn't dependent on the program but rather video encoding and transfer delays between parties.
